node {
   stage('Fetch changes') {
      git 'https://github.com/hienngu.git'
   }
   stage('Build image') {
      // Run Maven build 
      if (isUnix()) {
         sh "mvn -f ./api-gateway/pom.xml  -Pdockerimage docker:build"
      } else {
         echo "Not ready for windows"
      }
   }
   // Deploy ECS
   stage('Deploy ECS') {
      echo "TODO deploy on AWS"
   }
}