# Spring properties
spring:
  application:
     name: booking-service  # Service registers under this name
  # Added to fix -  java.lang.IllegalArgumentException: error at ::0 can't find referenced pointcut hystrixCommandAnnotationPointcut
  aop:
      auto: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


# Map the error path to error template (for Thymeleaf)
error:
  path=/error

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# HTTP Server
server:
  port: 8086   # HTTP (Tomcat) port

custom:
  fare:
    service:
      url: http://localhost:8085/fares


# Deregistration on shutdown
endpoints:
  shutdown:
    enabled: true
    sensitive: false 
    
