version: '3'
# RabbitMQ Management UI : http://localhost:15672/ - RabbitMQ image 
rabbitmq:
  image:  rabbitmq:3.6.1-management
  ports:
    - "5672:5672"
    - "15672:15672"

# MongoDB image 
mongodb:
  build:
      context: mongo
  image: mongo:3.4.4
  ports:
    - "27017:27017"
  deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


# MySQL instance image 




# PostgreSQL instance image 




# Cassandra image




# Redis image 
redis:
    image: redis:4.0.6
    ports:
      - "6379"3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

# RabbitMQ
rabbitmq:
    image: rabbitmq:3.7-management-alpine
    ports:
      - "5672"
      - "15672"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

services:
  checkout_db:
    image: postgres
    environment:
      - POSTGRES_USER=amqpadmin
      - POSTGRES_PASSWORD=amqpadmin
    ports:
      - "54321:5432"
    links:
      - eureka
    depends_on:
      - mongodb
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  delivery_db:
    image: postgres
    environment:
      - POSTGRES_USER=amqpadmin
      - POSTGRES_PASSWORD=amqpadmin
    ports:
      - "54322:5432"
  reports_db:
    image: postgres
    environment:
      - POSTGRES_USER=amqpadmin
      - POSTGRES_PASSWORD=amqpadmin
    ports:
      - "54323:5432"
  notifications_db:
    image: postgres
    environment:
      - POSTGRES_USER=amqpadmin
      - POSTGRES_PASSWORD=amqpadmin
    ports:
      - "54324:5432"
  rabbitmq_master:
    image: rabbitmq:3-management
    hostname: rabbitmq_master
    environment:
      - RABBITMQ_ERLANG_COOKIE="clusteramqp-01-2017"
    ports:
      - "8080:15672"
    depends_on:
      - rabbitmq_slave
  rabbitmq_slave:
    image: rabbitmq:3-management
    hostname: rabbitmq_slave
    environment:
      - RABBITMQ_ERLANG_COOKIE="clusteramqp-01-2017"
    ports:
      - "9080:15672"
  mail_server:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
  eureka:
    build: ../flightbooking/eureka-server
    ports:
      - "8761:8761"
  zuul:
    build: ../flightbooking/zuul-server
    links:
     - eureka
    ports:
      - "8080:8080"
  turbine:
    build: ../f
    links:
     - eureka
    ports:
      - "8989:8989"
  